### ISSUE TITLE
vGridBreakpointObject should only be available inside script tags not in the template

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify-vscode#2]
When i type vGridBreakBreakpointObject autocompletion only works inside a template tags.
Which Should be Inside a Script tag of a .vue files

**Comment by abhaywawale** [comment]
I did't get it. You used `vGridBreakPointObject` in template? Does it not work in script tag.

**Comment by abhaywawale** [comment]
Sorry for inconvenience. Next patch will fix it.

**Comment by abhaywawale** [comment]
v1.0.5 solves the problem and thanks for feedback.
